### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by willDTF** [OwenYou/DavinciResolveDCTL_ChromaticAdaptation#1]
Hi, just gived a test to your dctl, nothing happened at all in resolve, 
DCTL is well loaded but changing source / destination don't change the image at all
![image](https://user-images.githubusercontent.com/4272733/160394828-8e9abd15-001c-430a-8ad4-170f8550d06a.png)

**Comment by OwenYou** [comment]
This is probably because davinci resolve has updated its dctl syntax, this dctl requires an update to be properly functional.
Currently, I have no plan to do such a rewrite, an alternative choice is to use davinci resolve's chromatic adaptation OFX. The Bradford Linear method in that OFX does exactly the same as this DCTL will do.

**Comment by willDTF** [comment]
Ok, thanks for infos, i was curious to see how it change from resolve's one

cheers

**Comment by OwenYou** [comment]
As shown in the Demo Images.zip file, the result is 100% the same
from resolve's implementation.

By the way, I remember this dctl works fine under resolve 16.

best regards

William Eguienta ***@***.***> 于2022年3月28日周一 20:18写道：
